platform :ios, '11.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'Intercom', '9.3.1'
end